language: node_js
node_js:
  - "12.16.1"

install:
  - npm install newman
 
script: 
  - usr/lib/node_modules/newman/bin/newman.js run tests/Flask_API_Stores.postman_collection.json -e Testing tests/Testing-REST-Api.postman_environment.json

