language: node_js
node_js:
  - "12.16.1"

install:
  - npm init -y

before_script:
  - node --version
  - npm --version
  - newman --version
 
script: 
  - python app.py &
  - newman run tests/Flask_API_Stores.postman_collection.json -e tests/Testing-REST-Api.postman_environment.json

