language: node_js
node_js:
  - "12.16.1"

install:
  - npm install newman
 
script: 
  - usr/lib/node_modules/newman/bin/newman.js run tests/Flask API Stores.postman_collection.json -e Testing REST-Api of Flask-app.postman_environment.json 

